---
title: "detector evaluation"
output: html_document
---

504 frames were taken across all groups, half of them labeled as containing a face and half with no face.
```{r}
library(tidyverse)
library(magrittr)
```

Select detector to test:

MTCNN
```{r}
setwd("xs-face")
data <- read_csv("data/final_output/mtcnn3.csv") %>%
  distinct(video, frame, .keep_all = TRUE)

original_candidates <- read_csv("data/ground_truth/gold_set_candidates2.csv") %>%
  arrange(video, frame)

ground_truth_data <- read_csv("data/ground_truth/ground_truth3.csv") %>%
  select(-angle) %>%
  arrange(video, frame) %>%
  cbind(original_candidates %>%
          select(sample_type))
```

OPENPOSE
```{r}
setwd("xs-face")
data <- read_csv("data/final_output/openpose_results_truncated.csv") %>%
  distinct(name, frame, .keep_all = TRUE)

data %<>%
  mutate(is_face = ifelse(Nose_conf != 0, "True", "False"))%>%
  select(group, name, frame, is_face) %>%
  rename(video = name)

original_candidates <- read_csv("data/ground_truth/gold_set_candidates2.csv") %>%
  arrange(video, frame)

ground_truth_data <- read_csv("data/ground_truth/ground_truth3.csv") %>%
  select(-angle) %>%
  arrange(video, frame) %>%
  cbind(original_candidates %>%
          select(sample_type))
```

OPENPOSE WRISTS
```{r}
data <- read_csv("data/final_output/openpose_results_truncated_2.csv") %>%
  distinct(name, frame, .keep_all = TRUE)

data %<>%
  mutate(is_face = ifelse(LWrist_conf != 0 | RWrist_conf != 0, "True", "False"))%>%
  select(group, name, frame, is_face) %>%
  rename(video = name)

ground_truth_data <- read_csv("data/ground_truth/ground_truth_wrists.csv") %>%
  arrange(video, frame) %>%
  cbind(read_csv("data/ground_truth/gold_set_candidates2.csv") %>%
          arrange(video, frame) %>%
          select(sample_type))
```

OPENPOSE HANDS
```{r}
setwd("xs-face")
a <- read_csv("data/final_output/openpose_results_truncated.csv") %>%
  distinct(name, frame, .keep_all = TRUE)

data <- a %>%
  mutate(is_face = ifelse(LWrist_conf != 0 | RWrist_conf != 0, "True", "False")) %>%
  select(group, name, frame, is_face) %>%
  rename(video = name)

ground_truth_data <- read_csv("data/ground_truth/ground_truth_hands.csv") %>%
  select(-angle) %>%
  arrange(video, frame) %>%
  cbind(read_csv("data/ground_truth/gold_set_hand_candidates.csv") %>%
          arrange(video, frame) %>%
          select(sample_type))
```

OPENPOSE HAND DETAIL
```{r}
a <- read_csv("/Users/alessandro/workspace/openpose_results_with_detail.csv") %>%
  distinct(name, frame, .keep_all = TRUE)

data <- a %>%
 mutate(video = name) %>%
 distinct(video,frame,.keep_all=TRUE)  %>%
 #mutate(frame = as.numeric(frame)) %>%
 select(group, video,frame,ends_with("conf")) %>%
 mutate(confLeft=rowSums(.[grep("hand_left", names(.))])/21)  %>%
 mutate(confRight=rowSums(.[grep("hand_right", names(.))])/21)  %>%
 mutate(handOP = confRight>.2 | confLeft>.2 )
  #mutate(is_face = ifelse(LWrist_conf != 0 | RWrist_conf != 0, "True", "False"))%>%
  #select(group, name, frame, is_face) %>%
  # rename(video = name) %>%
  # select(group, video,frame,ends_with("conf")) %>%
  # mutate(confLeft=rowSums(.[grep("hand_left", names(.))])/21)  %>%
  # mutate(confRight=rowSums(.[grep("hand_right", names(.))])/21)  %>%
  # mutate(handOP = confRight>0 | confLeft>0 )

data %<>%
  mutate(is_face = ifelse(handOP, "True", "False")) 

ground_truth_data <- read_csv("data/ground_truth/ground_truth_hands.csv") %>%
  select(-angle) %>%
  arrange(video, frame) %>%
  cbind(read_csv("data/ground_truth/gold_set_hand_candidates.csv") %>%
          arrange(video, frame) %>%
          select(sample_type))
```

Join data
```{r}
combined <- data %>%
  rename(detector_is_face = is_face) %>%
  inner_join(ground_truth_data, by = c("group", "video", "frame"))
```


Eval function
```{r}
evaluate <- function(a, b) {
  if (a == "True") {
    if (a == b) return ("TP")
    else return("FN")
  }
  else {
    if (a == b) return("TN")
    else return("FP")
  }
}
```

Evaluate
```{r}
results <- combined %>%
  rowwise() %>%
  mutate(result = evaluate(is_face, detector_is_face))
```

Precison / Recall / F-score
```{r}
results %>%
  count(result)

# p <- score[4,2] / (score[4,2] + score[2,2])
# r <- score[4,2] / (score[4,2] + score[1,2])
# f <- 2 * p * r / (p + r)
# 
# print(paste("P:", round(p,3), "R:", round(r,3), "F:", round(f,3)))
```

