---
title: "reliability_analyses"
author: "Bria Long"
date: "7/27/2020"
output: html_document
---


# Step 0: Libraries and helper functions
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls()) # remove all objects from current workspace
library(dplyr)
library(readr)
library(magrittr)
library(tidyr)
library(lubridate)
library(irr)
library(forcats)
library(assertthat)
source("helper.R") # Contains critical helper functions for merging annotations
```

## Load basics
```{r}
# frame by video structure
load(file = '../data/consolidated_data/video_by_frame.RData')
```

## Naming reliabilty
```{r}
# paths to datafiles
file_path = '../data/naming/second/'
second_codes = dir(file_path) %>%
  tibble() %>%
  mutate(subid = str_split_fixed(., '-',2)[,1])

##
all_namings_second_coder <- all_dets_stripped %>%
  filter(subid %in% second_codes$subid) %>%
  do(add.times(.)) %>%  # calls helper functions to add times
  group_by(subid) %>%
  do(get.namings.second(.)) %>%
  rename(time_second_coder = time)  %>%
  select(-naming.instance) 
##
all_namings_first_coder <- all_dets_stripped %>%
  filter(subid %in% second_codes$subid) %>%
  do(add.times(.)) %>%  # calls helper functions to add times
  group_by(subid) %>%
  do(get.namings(.))  %>%
  rename(time_first_coder = time) %>%
  select(-naming.instance, -X) 

joined_namings_4s <- all_namings_first_coder %>%
  full_join(all_namings_second_coder) %>%
  mutate(time_lower = time_first_coder-2, time_upper = time_first_coder+2) %>%
  mutate(match = time_second_coder>=time_lower & time_second_coder<=time_upper) %>%
  group_by(subid, name, time_first_coder) %>%
  summarize(found_both = sum(match)>0) %>% 
  mutate(found_both = replace_na(found_both, FALSE))

joined_namings_2s <- all_namings_first_coder %>%
  full_join(all_namings_second_coder) %>%
  mutate(time_lower = time_first_coder-1, time_upper = time_first_coder+1) %>%
  mutate(match = time_second_coder>=time_lower & time_second_coder<=time_upper) %>%
  group_by(subid, name, time_first_coder) %>%
  summarize(found_both = sum(match)>0) %>% 
  mutate(found_both = replace_na(found_both, FALSE))

mean(joined_namings_4s$found_both)
mean(joined_namings_2s$found_both)

# if we want to examine second -> first coder reliability
#
# joined_namings_2 <- all_namings_second_coder %>%
#   full_join(all_namings_first_coder) %>%
#   mutate(time_lower = time_second_coder-2, time_upper = time_second_coder+2) %>%
#   mutate(match = time_first_coder>=time_lower & time_first_coder<=time_upper) %>%
#   group_by(subid, name, time_second_coder) %>%
#   summarize(found_both = sum(match)>0) %>%
#   mutate(found_both = replace_na(found_both, FALSE))

# mean(joined_namings_2$found_both, na.rm=TRUE)

```
We found that `r round(mean(joined_namings_4s$found_both),2)*100`% of naming events were detected within a 4 second window around the naming event, and `r round(mean(joined_namings_2s$found_both),2)*100`% of namings events were detected within a 2 second window.



```{r}
for_binning <- all_dets_stripped %>%
  filter(subid %in% second_codes$subid) %>%
  do(add.times(.))

bin_size = 3 # seconds
min_time = min(for_binning$time, na.rm=TRUE)
max_time = max(for_binning$time, na.rm=TRUE)
bin_starts = seq(min_time, max_time+1,bin_size)
bins = c(bin_starts, max_time)

test <- for_binning %>%
  select(subid, time) %>%
  mutate(time_bin = cut(time, bins, bin_starts))
  
```

## Posture reliability
```{r}

d <- all_dets_stripped %>%
  group_by(subid) %>% # get subid
  do(add.times(.)) %>%  # calls helper functions to add times
  group_by(subid) %>%
  do(add.posture(.)) %>% ## adds both postures and orientatinos
  do(add.posture.second(.)) ## and from a second coder...
```


```{r}
posture_reliability <- d %>%
  select(subid, frame, posture, posture_second, orientation, orientation_second) %>%
  mutate(posture = fct_explicit_na(posture,'NIF')) %>%
  mutate(posture_second = fct_explicit_na(posture_second,'NIF')) %>%
  filter(!posture=='NIF') %>%
  filter(!posture_second=='NIF')
  
col_names = c('rater1','rater2')
posture_eval = data.frame(posture_reliability$posture, posture_reliability$posture_second)
irr::kappa2(posture_eval)

orient_eval = data.frame(posture_reliability$orientation, posture_reliability$orientation_second)
irr::kappa2(orient_eval)


```


```{r}
coder_1 <- ggplot(posture_reliability, aes(x=frame, y=posture_second, fill=posture_second)) +
  geom_tile() +
  facet_wrap(~subid) + 
  theme(legend.position='none')

coder_2 <- ggplot(posture_reliability, aes(x=frame, y=posture, fill=posture)) +
  geom_tile() +
  facet_wrap(~subid) + 
  theme(legend.position='none')

cowplot::plot_grid(coder_1,coder_2, nrow=2)
```

```{r}
# posture_every_second <- d %>%
#   mutate(time_seconds = round(time,0)) %>%
#   group_by(time_seconds) %>%
#   mutate(common_posture = names(sort(table(posture)))[5],
#   common_posture_second = names(sort(table(posture_second)))[5])
# 
# posture_eval_second = data.frame(posture_every_second$common_posture, posture_every_second$common_posture_second)
# irr::kappa2(posture_eval_second)
```

