---
title: "get_gold_set_hand_images"
output: html_document
---

```{r}
library(tidyverse)
library(magrittr)
```

```{r}
setwd("/Users/alessandro/Github/xs-face")
data <- read_csv("data/final_output/openpose_results_truncated.csv")
```

```{r}
data2 <- data %>% 
  rename(video = name) %>%
  distinct(video, frame, .keep_all = TRUE)
```

Sample high density faces, remove selected from original data
```{r}
high_density_hands_sample <- data2 %>%
  group_by(video) %>%
  filter(LWrist_conf != 0 | RWrist_conf != 0) %>%
  sample_n(7) %>%
  mutate(sample_type = "high_density")

data3 <- data2 %>%
  anti_join(high_density_hands_sample)
```

Choose random frames from remaining
```{r}
random_sample <- data3 %>%
  group_by(video) %>%
  sample_n(7) %>%
  mutate(sample_type = "random")
```

Combine and save result
```{r}
gold_set_candidates <- high_density_hands_sample %>%
  rbind(random_sample) %>%
  mutate(path = paste0(video, "/image-", frame, ".jpg")) %>%
  arrange(video, frame)

write_csv(gold_set_candidates, "data/ground_truth/gold_set_hand_candidates.csv")
```



