---
title: "XS-FACE preliminary analysis"
output: html_notebook
---

Imports
```{r, message=FALSE, warning=FALSE}
library(knitr)
library(tidyverse)
```

Load CSV
```{r, message=FALSE, warning=FALSE}
data1 <- read_csv('/Users/alessandro/workspace/3.csv')
data <- read_csv("../data/final_output/mtcnn_face_detections.csv")
```

```{r}
setwd("..")
```

Summarize
```{r}
data1 %>%
  #filter(w>100 | is.na(w)) %>%
  distinct(group, video, frame, is_face) %>% # ignore > 1 face detections
  group_by(group) %>%
  summarise(face_frames=sum(is_face=="True"), total=n()) %>%
  mutate(percentage=face_frames/total * 100) %>%
  arrange(group) %>%
  kable
```


```{r}
b <- data %>%
  filter(video=="XS_0801", angle==0, is_face=="True") %>%
  arrange(frame) 

```

```{r}
a <- data %>% filter(angle ==0, is_face=="True") %>% sample_n(250)
b <- data %>% filter(angle ==0, is_face=="False") %>% sample_n(250)
c <- rbind(a, b)
c %>% mutate(path = paste0("/share/PI/mcfrank/frames/", group, "-months/", video, "/image-",frame,".jpg"))
write_csv(c, "sample.csv")
```

```{r}
val <- inner_join(c,gold, by = c("group", "video", "frame", "angle"))

```

```{r}
func <- function(a, b) {
  if (a == "True") {
    if (a == b) return ("TP")
    else return("FP")
  }
  else {
    if (a == b) return("TN")
    else return("FN")
  }
}
```

```{r}
answers <- val %>%
  rowwise() %>%
  mutate(ans = func(is_face.x, is_face.y))
```

```{r}
answers %>% 
  filter(ans == "TP") %>%
  nrow()
```

```{r}
answers %>% 
  filter(group == "8", ans == "FP") %>%
  nrow()
```

```{r}
answers %>% 
  filter(ans == "TN") %>%
  nrow()
```

```{r}
answers %>% 
  filter(ans == "FN") %>%
  nrow()
```

```{r}
b
table(diff(as.integer(distinct(a, frame)$frame)))
```

```{r}
diff(as.integer((b %>% filter(w < 100) %>% distinct(frame))$frame)) %>% table
```



```{r}
d8 <- data %>% 
  filter(group==8) %>%
  distinct(group, video, frame, is_face, angle) %>% 
  arrange(video, frame)
b
d8a <- d8 %>% 
  filter(angle==180)

d8b <- d8 %>%
  filter(angle==0)

hist(h$area, xlim=c(10, 40000), binwidth=10)
```

